name: cardessa
favicon: null
layout_spectrum: 0.7061022578272969
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#3e3e3e'
    - '#cdcdcd'
    - '#808080'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: sign-ups
    item: null
    url: null
typography_spectrum: 0.013905496569350362
